#!/bin/bash
username=`head -n1 $1 | tail -1`   
password=`head -n2 $1 | tail -1`
tm="$(date +%s)"
dt="$(date +'%Y-%m-%d %H:%M:%S')"

HOST='mysql2.blazingfast.io'
USER='ffastvpn_pro'
PASS='ffastvpn_pro'
DB='ffastvpn_pro'
PORT='3306'

##Authentication
VIP="user_name='$username' AND user_pass='$password' AND is_validated=1 AND frozen=0 AND is_vip=1 AND vip_duration > 0"
PRIV="user_name='$username' AND user_pass='$password' AND frozen=0 AND private_duration > 0"
Query="SELECT user_name FROM users WHERE $VIP OR $PRIV"
user_name=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`
[ "$user_name" != '' ] && [ "$user_name" = "$username" ] && echo "user : $username" && echo 'authentication ok.' && exit 0 || echo 'authentication failed.'; exit 1
